---
codecov:
  upload:
    overwrite: true
    env: CODECOV_ENV
  comment: true
  coverage:
    precision: 2
    round: up
    files:
      dynamic_array.h:
        target: 90
        message: Ensure adequate coverage for functions declared in dynamic_array.h