codecov:
  branch: stable

coverage:
  status:
    project:
      default: off
      dynamic_array:
        target: 10%  # Set the target coverage for dynamic_array.h
        flags:
          - dynamic_array

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes     
  branches: null  

flags:
  dynamic_array:
    paths: 
      - dynamic_array.h
    carryforward: true

