codecov:
  branch: stable

coverage:
  status:
    project:
      default: off
      dynamic_array:
        target: 35%
        flags:
          - dynamic_array

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes     
  branches: null
  message:
    flags:
      dynamic_array:
        failed:
          title: "Dynamic Array Coverage Check Failed"
          body: |
            The coverage for the **dynamic_array** flag is below the required threshold.
            Please ensure that your tests are adequately covering all code paths.  

flags:
  dynamic_array:
    paths: 
      - dynamic_array.h
    carryforward: true

