# codecov.yml
codecov:
  # Prevents accumulation of coverage data
  upload:
    # Setting this to true will overwrite the existing coverage report
    overwrite: true
    # Use the following to set a unique environment variable for the uploads
    env: CODECOV_ENV



